# **Replacing Fully-Connnected by Equivalent Convolutional Layers**

In [1]:
import torch

In [2]:
inputs = torch.tensor([[[[1., 2.],  [3., 4.]]]])
inputs.shape

torch.Size([1, 1, 2, 2])

## **Fully Connected**

In [3]:
fc = torch.nn.Linear(4, 2)

weights = torch.tensor([[1.1, 1.2, 1.3, 1.4],
                        [1.5, 1.6, 1.7, 1.8]])
bias = torch.tensor([1.9, 2.0])
fc.weight.data = weights
fc.bias.data = bias

In [4]:
torch.relu(fc(inputs.view(-1, 4)))

tensor([[14.9000, 19.0000]], grad_fn=<ReluBackward0>)

## **Convolution with Kernels equal to the input size**

![](../images/fc-to-conv/fc-to-conv-1.png)

In [5]:
conv = torch.nn.Conv2d(in_channels=1, out_channels=2, kernel_size=inputs.squeeze(dim=(0)).squeeze(dim=(0)).size())

In [6]:
print(conv.weight.size())
print(conv.bias.size())

torch.Size([2, 1, 2, 2])
torch.Size([2])


In [7]:
conv.weight.data = weights.view(2, 1, 2, 2)
conv.bias.data = bias

In [8]:
torch.relu(conv(inputs))

tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)

## **Convolution with 1x1 Kernels**

In [9]:
conv = torch.nn.Conv2d(in_channels=4, out_channels=2, kernel_size=(1, 1))

In [10]:
conv.weight.data = weights.view(2, 4, 1, 1)
conv.bias.data = bias
torch.relu(conv(inputs.view(1, 4, 1, 1)))

tensor([[[[14.9000]],

         [[19.0000]]]], grad_fn=<ReluBackward0>)