# Generating Validation Set Splits

## A Typical Dataset (here: MNIST)

In [9]:
import torch
from torchvision import datasets
from torchvision import transforms
from torch.utils.data import DataLoader

BATCH_SIZE = 64

## MNIST DATASET

In [10]:
train_dataset = datasets.MNIST(root='data', 
                               train=True, 
                               transform=transforms.ToTensor(),
                               download=True)

test_dataset = datasets.MNIST(root='data', 
                              train=False, 
                              transform=transforms.ToTensor())

train_loader = DataLoader(dataset=train_dataset, 
                          batch_size=BATCH_SIZE,
                          num_workers=4,
                          shuffle=True)

test_loader = DataLoader(dataset=test_dataset, 
                         batch_size=BATCH_SIZE,
                         num_workers=4,
                         shuffle=False)

In [11]:
for images, labels in train_loader:  
    print('Image batch dimensions:', images.shape)
    print('Image label dimensions:', labels.shape)
    break

Image batch dimensions: torch.Size([64, 1, 28, 28])
Image label dimensions: torch.Size([64])


In [12]:
print(f'Total number of training examples: {len(train_dataset)}')

Total number of training examples: 60000


## Subset Method

In [13]:
from torch.utils.data.dataset import Subset

In [14]:
valid_indices = torch.arange(0, 1000)
train_indices = torch.arange(1000, 60000)


train_and_valid = datasets.MNIST(root='data', 
                                 train=True, 
                                 transform=transforms.ToTensor(),
                                 download=True)

train_dataset = Subset(train_and_valid, train_indices)
valid_dataset = Subset(train_and_valid, valid_indices)

In [15]:
train_loader = DataLoader(dataset=train_dataset, 
                          batch_size=BATCH_SIZE,
                          num_workers=4,
                          shuffle=True)

valid_loader = DataLoader(dataset=valid_dataset, 
                          batch_size=BATCH_SIZE,
                          num_workers=4,
                          shuffle=False)

In [16]:
# Checking the dataset
for images, labels in train_loader:  
    print('Image batch dimensions:', images.shape)
    print('Image label dimensions:', labels.shape)
    break

Image batch dimensions: torch.Size([64, 1, 28, 28])
Image label dimensions: torch.Size([64])


In [17]:
for images, labels in train_loader:  
    pass
print(labels[:10])

for images, labels in train_loader:  
    pass
print(labels[:10])

tensor([6, 7, 1, 0, 2, 4, 7, 3, 9, 8])
tensor([1, 1, 2, 4, 6, 7, 3, 1, 5, 8])


In [18]:
torch.manual_seed(123)
for images, labels in train_loader:  
    pass
print(labels[:10])

torch.manual_seed(123)
for images, labels in train_loader:  
    pass
print(labels[:10])

tensor([9, 5, 1, 9, 0, 9, 2, 3, 7, 3])
tensor([9, 5, 1, 9, 0, 9, 2, 3, 7, 3])


## SubsetRandomSampler Method

In [19]:
from torch.utils.data import SubsetRandomSampler

In [20]:
train_indices = torch.arange(1000, 60000)
valid_indices = torch.arange(0, 1000)

train_sampler = SubsetRandomSampler(train_indices)
valid_sampler = SubsetRandomSampler(valid_indices)

training_transform = transforms.Compose([transforms.Resize((32, 32)),
                                         transforms.RandomCrop((28, 28)),
                                         transforms.ToTensor()])

valid_transform = transforms.Compose([transforms.Resize((32, 32)),
                                         transforms.CenterCrop((28, 28)),
                                         transforms.ToTensor()])

train_dataset = datasets.MNIST(root='data', 
                               train=True, 
                               transform=training_transform,
                               download=True)

valid_dataset = datasets.MNIST(root='data', 
                               train=True, 
                               transform=valid_transform,
                               download=False)

test_dataset = datasets.MNIST(root='data', 
                              train=False, 
                              transform=valid_transform,
                              download=False)

train_loader = DataLoader(train_dataset,
                          batch_size=BATCH_SIZE,
                          num_workers=4,
                          sampler=train_sampler)

valid_loader = DataLoader(valid_dataset,
                          batch_size=BATCH_SIZE,
                          num_workers=4,
                          sampler=valid_sampler)

test_loader = DataLoader(dataset=test_dataset, 
                         batch_size=BATCH_SIZE,
                         num_workers=4,
                         shuffle=False)

In [21]:
for images, labels in train_loader:  
    print('Image batch dimensions:', images.shape)
    print('Image label dimensions:', labels.shape)
    break

Image batch dimensions: torch.Size([64, 1, 28, 28])
Image label dimensions: torch.Size([64])


In [22]:
for images, labels in train_loader:  
    pass
print(labels[:10])

for images, labels in train_loader:  
    pass
print(labels[:10])

tensor([7, 0, 3, 6, 6, 7, 0, 8, 8, 4])
tensor([5, 7, 9, 3, 7, 2, 1, 6, 6, 4])


In [23]:
torch.manual_seed(123)
for images, labels in train_loader:  
    pass
print(labels[:10])

torch.manual_seed(123)
for images, labels in train_loader:  
    pass
print(labels[:10])

tensor([1, 0, 3, 7, 0, 7, 5, 6, 8, 3])
tensor([1, 0, 3, 7, 0, 7, 5, 6, 8, 3])
